export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_FEATURED = 'ADD_TO_FEATURED';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_SINGLE_ITEM_FROM_CART = 'REMOVE_SINGLE_ITEM_FROM_CART';
export const SHOW_HIDE_CART = 'SHOW_HIDE_CART';
